prima: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/staging/prima/CORE/HDD/src/wlan_hdd_oemdata.c:1004:28: error: a functi
on declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void oem_deactivate_service()
                           ^
                            void

drivers/staging/prima/CORE/HDD/src/wlan_hdd_main.c:8777:35: error: a function
declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int hdd_open_cesium_nl_sock()
                                  ^
                                   void

drivers/staging/prima/CORE/HDD/src/wlan_hdd_main.c:8808:37: error: a function
declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static void hdd_close_cesium_nl_sock()
                                    ^
                                     void

drivers/staging/prima/CORE/HDD/src/wlan_hdd_trace.c:134:18: error: a function
declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void hddTraceInit()
                 ^
                  void

drivers/staging/prima/CORE/HDD/src/wlan_hdd_trace.c:196:33: error: a function
declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void hdd_register_debug_callback()
                                ^
                                 void

drivers/staging/prima/CORE/SVC/src/nlink/wlan_nlink_srv.c:407:26: error: a func
tion declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int nl_srv_is_initialized()
                         ^
                          void

drivers/staging/prima/CORE/SVC/src/btc/wlan_btc_svc.c:228:28: error: a function
 declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void btc_deactivate_service()
                           ^
                            void

drivers/staging/prima/CORE/SVC/src/logging/wlan_logging_sock_svc.c:597:38: erro
r: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void wlan_disable_and_flush_pkt_stats()
                                     ^
                                      void

drivers/staging/prima/CORE/SVC/src/logging/wlan_logging_sock_svc.c:1997:36: err
or: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void wlan_flush_host_logs_for_fatal()
                                   ^
                                    void

drivers/staging/prima/CORE/SVC/src/logging/wlan_logging_sock_svc.c:2063:54: err
or: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
bool wlan_fwr_mem_dump_test_and_set_write_allowed_bit(){
                                                     ^
                                                      void
drivers/staging/prima/CORE/SVC/src/logging/wlan_logging_sock_svc.c:2086:53: err
or: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
bool wlan_fwr_mem_dump_test_and_set_read_allowed_bit(){
                                                    ^
                                                     void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>