media: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warning:

drivers/media/platform/msm/vidc/msm_vidc_common.c:2520:35: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void msm_comm_handle_thermal_event()
                                  ^
                                   void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>