video: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warning:

drivers/video/fbdev/msm/../../msm/mdss/mdss_util.c:240:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototyp
es]
struct mdss_util_intf *mdss_get_util_intf()
                                         ^
                                          void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>