tty: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/tty/diag/tty_diag.c:318:38: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void tty_diag_channel_abandon_request()
                                     ^
                                      void

drivers/tty/diag/tty_diag.c:328:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int tty_diag_get_dbg_ftm_flag_value()
                                   ^
                                    void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>