video: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/video/fbdev/msm/../../msm/mdss/mdss_mdp.c:4456:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct irq_info *mdss_intr_line()
                               ^
                                void

drivers/video/slimport/anx7805/slimport_tx_drv.c:3702:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void SP_TX_Config_MIPI_Video_Format()
                                   ^
                                    void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>