fusb: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/misc/fusb302/core/vdm/vdm.c:74:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
FSC_S32 initializeVdm()
                     ^
                      void

drivers/misc/fusb302/core/vdm/vdm.c:1025:26: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void sendVdmMessageFailed()
                         ^
                          void

drivers/misc/fusb302/core/vdm/vdm_callbacks.c:52:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
Identity vdmRequestIdentityInfo()
                               ^
                                void

drivers/misc/fusb302/core/vdm/vdm_callbacks.c:66:28: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
SvidInfo vdmRequestSvidInfo()
                           ^
                            void

drivers/misc/fusb302/core/vdm/vdm_callbacks.c:215:16: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void vdmInitDpm()
               ^
                void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>