input: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/input/sensors/smi130/smi130_gyro.c:1399:60: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
SMI130_GYRO_RETURN_FUNCTION_TYPE smi130_gyro_set_soft_reset()
                                                           ^
                                                            void

drivers/input/sensors/smi130/smi130_gyro.c:5262:64: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
SMI130_GYRO_RETURN_FUNCTION_TYPE smi130_gyro_enable_fast_offset()
                                                               ^
                                                                void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>