soc: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warning:

drivers/soc/qcom/qdsp6v2/voice_svc.c:600:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int voice_svc_dummy_reg()
                              ^
                               void

Change-Id: I7bbd3a00f3407fc11a5cd1a9515e8af9c65289f2
Signed-off-by: SirRGB <sirrgb@proton.me>