char: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/char/diag/diagchar_core.c:3339:18: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_init()
                 ^
                  void

drivers/char/diag/diagchar_core.c:3365:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_on_notify()
                      ^
                       void

drivers/char/diag/diagchar_core.c:3508:21: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_ws_release()
                    ^
                     void

drivers/char/diag/diag_mux.c:52:18: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int diag_mux_init()
                 ^
                  void

drivers/char/diag/diag_mux.c:79:19: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_mux_exit()
                  ^
                   void

drivers/char/diag/diag_memorydevice.c:85:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_md_open_all()
                     ^
                      void

drivers/char/diag/diag_memorydevice.c:101:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_md_close_all()
                      ^
                       void

drivers/char/diag/diag_dci.c:343:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void diag_dci_wakeup_clients()
                            ^
                             void

Change-Id: Ifd95b57d19a25f0932e5de8ec4de2f2c1e7e1259
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>